import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { heritageApi } from "../api";
export default function HeritagePage() {
    const [zoomImg, setZoomImg] = useState(null);
    const { data: res, isLoading } = useQuery({ queryKey: ["heritage"], queryFn: () => heritageApi.getAll() });
    const stories = res?.data?.data ?? [];
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "page-header", children: _jsxs("div", { children: [_jsx("h1", { children: "Heritage Stories" }), _jsx("p", { children: "The living legacy of India's carving traditions" })] }) }), isLoading && _jsx("div", { className: "loading", children: "Loading heritage stories\u2026" }), _jsx("div", { style: { display: "flex", flexDirection: "column", gap: 40 }, children: stories.map((s) => (_jsxs("div", { className: "heritage-card", children: [_jsx("img", { className: "heritage-cover", src: s.coverImage, alt: s.title }), _jsxs("div", { className: "heritage-body", children: [_jsxs("div", { style: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }, children: [_jsx("span", { className: "badge", style: { background: "#FEF3C7", color: "#92400E" }, children: s.style }), _jsxs("span", { style: { fontSize: "0.8rem", color: "var(--muted)" }, children: [s.period, " \u00B7 ", s.region] })] }), _jsx("h2", { style: { fontFamily: "Playfair Display,serif", fontSize: "1.6rem" }, children: s.title }), _jsx("p", { style: { color: "var(--muted)", fontStyle: "italic", marginTop: 4 }, children: s.subtitle }), _jsx("hr", { className: "divider" }), _jsx("p", { style: { whiteSpace: "pre-line", lineHeight: 1.8, fontSize: "0.9rem" }, children: s.content }), _jsx("hr", { className: "divider" }), _jsx("h4", { style: { marginBottom: 10, fontFamily: "Playfair Display,serif" }, children: "Key Features" }), _jsx("div", { className: "heritage-features", children: s.keyFeatures.map((f, i) => (_jsxs("span", { className: "feature-tag", children: ["\u2726 ", f] }, i))) }), s.gallery.length > 0 && (_jsxs(_Fragment, { children: [_jsx("h4", { style: { margin: "24px 0 12px", fontFamily: "Playfair Display,serif" }, children: "Gallery" }), _jsx("div", { className: "modal-gallery", children: s.gallery.map((img, i) => (_jsx("img", { src: img, alt: `${s.style} ${i}`, onClick: () => setZoomImg(img) }, i))) })] }))] })] }, s.id))) }), zoomImg && (_jsxs("div", { className: "zoom-overlay", onClick: () => setZoomImg(null), children: [_jsx("button", { className: "zoom-close", onClick: () => setZoomImg(null), children: "\u2715 Close" }), _jsx("img", { src: zoomImg, alt: "zoomed" })] }))] }));
}
